### ISSUE TITLE
How to select recompute number?

### ISSUE THREAD

**Issue by Hibb-bb** [ddkang/loss_dropper#3]
Hi, I'm trying to use this technique in my project. But I'm not sure that how to select a right value for recompute amount?
Should it based on dataset size?
Thank you.

**Comment by ddkang** [comment]
What is the "recompute amount" you are referring to?

**Comment by Hibb-bb** [comment]
The parameter in LossDropper class.
Thank you.

**Comment by ddkang** [comment]
The default values should work well - just make sure that `min_count >= recompute` and that `recompute <= dataset_size`

**Comment by Hibb-bb** [comment]
Got it, thanks!
